package View;

import java.util.List;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Random;
import javax.swing.Timer;
import model.Players;
import model.Round;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author José
 */
public class MainMenu extends javax.swing.JFrame {
    Round r = new Round();
    int min = 00, sec = 00;
    /**
     * Creates new form MainMenu
     */
    public MainMenu(){
        
        initComponents();
        
    }   
    public void Cronometro(int tipotarefa){
        if(tipotarefa == 1){
            //aqui startar o cronômetro de tempo para criarem as respostas (com base no tempo escolhido no menu NewGame)
            Timer cronometro = new Timer(1000, new Tarefa());
            cronometro.start();
        }else if(tipotarefa == 2){
            //aqui startar o cronômetro para adicionar as respostas de cada player no jogo (cerca de 1 min, dependendo da quantidade)
            Timer cronometro = new Timer(1000, new Tarefa2());
            cronometro.start();     
        }
    }
    
    class Tarefa implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent e) {
            //cronômetro para criarem as respostas (com base no tempo escolhido no menu NewGame)
            if(sec == 00 && min > 00){
                sec = 59;
                min -= 1;
                cronometroJLabel.setText(min + ":" + sec);
            }else if(sec > 0 && min >= 00){
                sec -= 1;
                cronometroJLabel.setText(min + ":" + sec);
            }else{
                cronometroJLabel.setText(min + ":" + sec);
                //aqui vai a ação que para a terefa (dispara uma janela)
            }
        }
    }
    
    class Tarefa2 implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent e){
        //cronômetro para adicionar as respostas de cada player no jogo (cerca de 1 min, dependendo da quantidade de respostas)
            if(sec == 00 && min > 00){
                sec = 59;
                min -= 1;
                cronometroJLabel.setText(min + ":" + sec);
            }else if(sec > 0 && min >= 00){
                sec -= 1;
                cronometroJLabel.setText(min + ":" + sec);
            }else{
                cronometroJLabel.setText(min + ":" + sec);
                //aqui vai a ação que para a tarefa (dispara uma janela)
            }
        }
    }
    
    public String randomizeWords(Players px){
        //cria a frase randomizada com base na frase enviada por cada player (pega do objeto Players)
        MainMenu m = new MainMenu();
        Random rand = new Random();
        List<Integer> seq = new ArrayList<>();
        String[] fraseOrdenada = px.getFrase().split(" ");
        String fraseReordenada;
        int i;
        
        for(i = 0; i < fraseOrdenada.length; i++){
            seq.add(i);
        }
        
        Collections.shuffle(seq);
        
        fraseReordenada = "<html><p><b>Frase de " + px.getNome() + ":</b></p>\n" + "<p><b>\"";
        
        for(i = 0; i < fraseOrdenada.length; i++){
            fraseReordenada += fraseOrdenada[seq.get(i)] + " ";
        }
        
        fraseReordenada += "\"</b></p></html>";
                
        return fraseReordenada;
        
    }    
    
    //||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cronometroJLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel = new javax.swing.JLabel();
        fraseJLabel = new javax.swing.JLabel();
        roundJLabel = new javax.swing.JLabel();
        novoJogoJButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Shaked Words");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setIconImages(null);

        cronometroJLabel.setBackground(new java.awt.Color(166, 0, 2));
        cronometroJLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        cronometroJLabel.setForeground(new java.awt.Color(255, 255, 255));
        cronometroJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cronometroJLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cronometroJLabel.setOpaque(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255), 2));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.setAlignmentX(1.0F);
        jLabel1.setAlignmentY(1.0F);
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 204, 51), new java.awt.Color(255, 153, 0), new java.awt.Color(255, 51, 0), new java.awt.Color(255, 102, 0)));
        jLabel1.setOpaque(true);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel.setBackground(new java.awt.Color(255, 255, 255));
        jLabel.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel.setAlignmentX(1.0F);
        jLabel.setAlignmentY(1.0F);
        jLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 153), new java.awt.Color(0, 204, 255), new java.awt.Color(0, 0, 102), new java.awt.Color(0, 102, 204)));
        jLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel.setOpaque(true);
        jLabel.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );

        fraseJLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        fraseJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fraseJLabel.setText("exemplo 1");
        fraseJLabel.setOpaque(true);

        roundJLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        roundJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        roundJLabel.setText("exemplo 2");
        roundJLabel.setOpaque(true);

        novoJogoJButton.setBackground(new java.awt.Color(102, 255, 102));
        novoJogoJButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        novoJogoJButton.setText("Novo Jogo");
        novoJogoJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoJogoJButtonActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Jogador/Frase");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fraseJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(roundJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(novoJogoJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cronometroJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(roundJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(fraseJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cronometroJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(novoJogoJButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void novoJogoJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoJogoJButtonActionPerformed
        NewGame ng = new NewGame();
        ng.setLocationRelativeTo(this);
        ng.setVisible(true);

    }//GEN-LAST:event_novoJogoJButtonActionPerformed

    Players px;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MainMenu m = new MainMenu();
        FormPlayer fp = new FormPlayer(jLabel1, min);
        fp.setLocationRelativeTo(this);
        fp.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
               MainMenu menu = new MainMenu();
               menu.setLocationRelativeTo(menu);
               menu.setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cronometroJLabel;
    private javax.swing.JLabel fraseJLabel;
    private javax.swing.JButton jButton1;
    protected javax.swing.JLabel jLabel;
    protected javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton novoJogoJButton;
    private javax.swing.JLabel roundJLabel;
    // End of variables declaration//GEN-END:variables
}
