/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author José
 */
public class NewGame extends javax.swing.JFrame {

    /**
     * Creates new form NewGame
     */
    public NewGame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numPlayersJLabel = new javax.swing.JLabel();
        roundTimeJLabel = new javax.swing.JLabel();
        playersNamesJLabel = new javax.swing.JLabel();
        addPlayerJButton = new javax.swing.JButton();
        timeJFormattedTextField = new javax.swing.JFormattedTextField();
        numPlayersJFormattedTextField = new javax.swing.JFormattedTextField();
        startJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAutoRequestFocus(false);
        setResizable(false);

        numPlayersJLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        numPlayersJLabel.setText("Quantidade de Jogadores");

        roundTimeJLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        roundTimeJLabel.setText("Cronômetro da Rodada (min)");

        playersNamesJLabel.setBackground(new java.awt.Color(255, 255, 255));
        playersNamesJLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        playersNamesJLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        playersNamesJLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        addPlayerJButton.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        addPlayerJButton.setText("Adicionar Jogador");
        addPlayerJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPlayerJButtonActionPerformed(evt);
            }
        });

        try {
            timeJFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        timeJFormattedTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        try {
            numPlayersJFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        startJButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        startJButton.setText("Start Game");
        startJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addPlayerJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(startJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(playersNamesJLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(numPlayersJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(numPlayersJFormattedTextField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(timeJFormattedTextField)
                            .addComponent(roundTimeJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numPlayersJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roundTimeJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(timeJFormattedTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(numPlayersJFormattedTextField))
                .addGap(18, 18, 18)
                .addComponent(playersNamesJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(startJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addPlayerJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addPlayerJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPlayerJButtonActionPerformed
 
    	FormPlayer dialog = new FormPlayer(playersNamesJLabel, 2);
        dialog.setVisible(true);
    	
    	
    }//GEN-LAST:event_addPlayerJButtonActionPerformed

    private void startJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startJButtonActionPerformed
        MainMenu m = new MainMenu();
        m.min = Integer.parseInt(timeJFormattedTextField.getText());
    }//GEN-LAST:event_startJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPlayerJButton;
    private javax.swing.JFormattedTextField numPlayersJFormattedTextField;
    private javax.swing.JLabel numPlayersJLabel;
    private javax.swing.JLabel playersNamesJLabel;
    private javax.swing.JLabel roundTimeJLabel;
    private javax.swing.JButton startJButton;
    private javax.swing.JFormattedTextField timeJFormattedTextField;
    // End of variables declaration//GEN-END:variables
}
